version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@agentica/*"
      - dependency-name: "tgrid"
      - dependency-name: "@tailwindcss/vite"
      - dependency-name: "vite"
      - dependency-name: "react*"
      - dependency-name: "typescript"
      - dependency-name: "@types/react"
      - dependency-name: "@vitejs/plugin-react"
      - dependency-name: "tailwindcss"

    groups:
      Agent:
        patterns:
          - "@agentica/*"
          - "tgrid"
      React:
        patterns:
          - "react*"
          - "@tailwindcss/vite"
          - "vite"
          - "@types/react*"
          - "@vitejs/plugin-react"
          - "tailwindcss"
      TypeScript:
        patterns:
          - "typescript"
